### ISSUE TITLE
On SIGINT, close the RabbitMQ connection

### ISSUE THREAD

**Issue by jpwilliams** [jpwilliams/remit#10]

**Comment by jpwilliams** [comment]
It'd be nice if we also add a `remit.close()` method that this runs so clients could manually trigger it.

**Comment by jacktuck** [comment]
+1 This is nice, esp. for scripts. We'd have to clean up all the event listeners too?

**Comment by jpwilliams** [comment]
Yeah. We'll work on being able to `.destroy()` everything and then we can have Remit roll back through.

In the new `v2` branch, all endpoint/listener/request/emission instances are created through a wrapper, so we can even keep track on these on the Remit class itself so that we can loop through and shut things down as we go.

Because of the way we now handle messages too, we can make sure that we stop consuming but finish any remaining unacked messages before closing things down.

Will be lovely.

**Comment by jpwilliams** [comment]
We'll add the ability to stop elsewhere, and then clients can hook in to signals and use the close methods if they wish.
