### ISSUE TITLE
Add the ability to proxy requests

### ISSUE THREAD

**Issue by jpwilliams** [jpwilliams/remit#13]
Using queue binding, we could "_proxy_" requests from one queue to another.

For example, you may wish to phase out a service in lieu of another and so proxy requests to the old service endpoints to new ones during the transition phase.

We could achieve this by binding the old queue name (as a routing key) to the new queue.
We may also have to remove the binding from the old queue?

Needs some playing around.

**Comment by jacktuck** [comment]
Arguably this could also be achieved via the listener chaining pattern we discussed earlier.

``
remit
  .endpoint('addFive', addFive)
  .endpoint('add5' addFive)

remit
  .listen('addedFive', addedFive)
  .listen('added5' addedFive)
``

Whether this is feasible or not, i am not sure, haha.

**Comment by jpwilliams** [comment]
The only confusing part here is that it feels like I can do:

``` js
remit
  .endpoint('foo')
  .request('bar')
  .send()
```

Maybe instead we add `proxy` function? Not sure if that's more understandable than duplicating `endpoint`/`listen` or not.

``` js
remit
  .endpoint('foo')
  .proxy('bar')

remit
  .listen('foo')
  .proxy('bar')
```

**Comment by jacktuck** [comment]
I like ~proxy~ `alias`, but yeah having that's not bad. Again i kinda thing supporting fewer patterns is better (RE. `remit.request('foo').send()` vs `remit.request('foo')()`)

**Comment by jpwilliams** [comment]
Closing as haven't found any firm requirement for this.
