### ISSUE TITLE
Add "latches" to help with idempotency issues for complex insertions

### ISSUE THREAD

**Issue by jpwilliams** [jpwilliams/remit#15]
When performing complex insertions using a single message in situations where everything must succeed otherwise the entire operation should fail, it's really difficult to achieve idempotency.

For example, a call to the endpoint `team.create` might also create the first user of a team. If creating the team succeeds but creating the user fails, the team should be deleted. This makes a listener pattern illogical. The route to create this via code can be a bit mad, but might be more achievable using "latches".

Using pseudo-code:

``` js
remit.res('team.create', function createTeam (args, done) {
  // create a latch that, upon being either released through code
  // with an error or because of the service dying, will send a 
  // message with the given routing key
  const latch = remit.latch('team.create.revert', args)

  // perform our tasks
  const teamErr = createTeam(args.name)
  const userErr = createUser(args.username)

  // release the latch
  // if a truthy error is given, send the message
  latch.release(teamErr || userErr)

  return done(teamErr || userErr)
})

// here we handle that latch being fired by deleting the team and user being created
remit.res('team.create.revert', function revertCreateTeam (args, done) {
  deleteTeam(args.name)
  deleteUser(args.username)

  return done()
})
```

One thing to discuss is whether we need an `addData` method on the returned latch to continue adding items. I currently see this as a bad idea, as it gives the _illusion_ of safety where there is none.

For example:

``` js
remit.res('...', function doSomething (args, done) {
  const latch = remit.latch('undo.something')

  doIt((err, insertedId) => {
    // if the service died after running `latch.addData`, we'd be fine
    // and would be able to properly revert the change.
    // however, if we failed _before_ running `latch.addData` but _after_
    // successfully inserting it, we'd most definitely be unable to remove it.

    // it seems like a bad idea, as it lures developers into thinking they're being
    // safe when there's still a risk
    latch.addData({insertedId: insertedId})
  })
})
```

With that in mind, it'd be most sensible to _always_ send the arguments the original function was given to the latch, meaning we should probably announce that a latch is present somewhere in the endpoint instantiation rather than within the callback. There is a case for only creating a latch in certain situations, such as an endpoint that creates an entity may be configured to return an existing entity with the same name if it's found and only create if it is not, meaning we'd only want a latch if there wasn't another item found.

There's also currently a bug with the current design whereby:

1. Service receives `team.create` message
2. Service creates `team.create.revert` latch
3. Service dies whilst creating team
4. `team.create` message and `team.create.revert` message are now both queued, meaning it might create-and-delete it instantaneously.

Even if we ack the original message as soon as a latch is set, we then run in to:

1. Service receives `team.create` message
2. Service creates `team.create.revert` latch
3. Service dies before checking if team already exists
4. `team.create.revert` message is sent to delete the team that already exists. Bummer.

Lots of bugs about it, but some interesting cases where it might be useful if we work out some kinks.

**Comment by jacktuck** [comment]
> For example, a call to the endpoint team.create might also create the first user of a team. If creating the team succeeds but creating the user fails, the team should be deleted. This makes a listener pattern illogical. 

I think this is conflating idempotency with what seem like the semantics of transactions.

And i think this is something that the transport should be completely dumb about and leave it up to users to sort something elsewhere.
