### ISSUE TITLE
Add noAck usage as a separate res type

### ISSUE THREAD

**Issue by jpwilliams** [jpwilliams/remit#18]
Some endpoints (the primary example being a push notification example from @jacktuck) require the ability to ack messages as they come in, meaning failed deliveries would never retry accidentally.

This can be achieved using `noAck` when consuming: 

> noAck (boolean): if true, the broker won't expect an acknowledgement of messages delivered to this consumer; i.e., it will dequeue messages as soon as they've been sent down the wire. Defaults to false (i.e., you will be expected to acknowledge messages).*

One option would be to add the ability to send consumption options into `.res()`, though our `noAck` example would require some extra details anyway, as:

> It's an error to supply a message that either doesn't require acknowledgement, or has already been acknowledged. Doing so will errorise the channel. *

Our best bet would probably be to add another endpoint type like `.ares()` to cater for this.

_* source: [amqplib | Channel API reference](http://www.squaremobius.net/amqp.node/channel_api.html)_

**Comment by jacktuck** [comment]
@jpwilliams Thanks. Want me to give this a shot?
