### ISSUE TITLE
Failing to create a queue (due to an assertion error) does not stop the process

### ISSUE THREAD

**Issue by jpwilliams** [jpwilliams/remit#38]
This usually comes when upgrading from remit v1 to v2 where priority settings on queues are different to before. How do we go about throwing so that the process stops?

It's being caught and calmly logged somewhere. We shouldn't do that.

**Comment by jacktuck** [comment]
How about a cheeky process.exit?

**Comment by jpwilliams** [comment]
Because endpoints and listeners now require the client to `.start()` them, we can have that returned Promise throw rather than having the power to kill the process.

``` js
try {
  remit.endpoint('foo', console.log).start()
} catch (e) {
  console.log('Endpoint failed to start.')
}
```
