### ISSUE TITLE
Multiple data listeners on endpoints are confusing

### ISSUE THREAD

**Issue by jpwilliams** [jpwilliams/remit#39]
Currently, endpoints of any sort can have multiple `data` listeners registered. All of these listeners can return Promises or run the `callback` provided, so there's a huge potential for races happening where the first past the post is the one to reply.

The proposition here is to instead have the current `data` listeners alongside an endpoint `handler`. The `handler` would be a single entity responsible for responding to incoming data. Once this `handler` resolves, returns it's `callback` or _synchronously_ returns if no `callback` is mapped and no `Promise` is returned, the message will be acked and the response sent back.

This will stand entirely separate from the `data` listeners, which will be "fire-and-forget" listeners to incoming events. No callback. No returns.

**Comment by jacktuck** [comment]
IMO we could just expose event emitter so people can listen to whatever. This should be a familiar pattern. Then we can keep `.data()` as the handler if that is desired?

**Comment by jacktuck** [comment]
```
let add5 = remit
  .request('add5')
  .on('error', function(data) { })
  .on('completed', function(data) { })

const y = await add5(1) // 6
const z = await add5.data(2) // 7

remit
  .endpoint('add5')
  .data(async x => x + 5)
  .on('error', function(data) { })
  .on('completed', function(data) { })
```

**Comment by jpwilliams** [comment]
I like that. The idea of making listeners more obvious by providing access to a familiar `on` interface is good. In fact, it makes the entire module more accessible.

Currently, the internals of _remit_ dictate that _exposing_ the interface wouldn't work; `data` never actually gets emitted in any usable form. We could rework this, however, so that the emitters are never used for message _handling_, meaning we free them up to emit proper events like `data` and `error` and use `handler`s for actually handling data.

Keeping `data` would be fine, but it feels a little ambiguously named if we're switching to have `on` around the place. Would `handler` be a better name? As well as that, running `.data()` on a request feels like I'm _setting_ the data to go out rather than requesting it.

Maybe some better semantics would be to switch to `success`/`failure`?

``` js
const add5 = remit
  .request('add5')

add5
  .on('failure', (err) => { ... })
  .on('success', (data) => { ... })

const y = await add5(1)
const z = await add5.send(2)

remit
  .endpoint('add5')
  .handler(async x => x + 5)
  .on('failure', (err) => { ... }) // something went wrong or an error was returned
  .on('success', (data) => { ... }) // data from successful response
  .on('data', (data) => { ... }) // data from incoming message
```

**Comment by jacktuck** [comment]
I like that a lot.

What about a listener for messages that are not ack'd within _x_ time -- could emit a `.on('stalled')`?

Of course it could only be treated as a hint since the endpoint could just be slow or having to do a lot of work

**Comment by jpwilliams** [comment]
Aye nah that is a good idea. Even a generic warning fired from remit that did `console.warn` or something would be nice to have.

The only issue I can currently see with this set-up is the difference in handling data between `endpoint`s and `listen`ers.

Endpoints do not currently acknowledge messages, as the messages themselves are transient (only exist for a limited amount of time), so queueing the messages seems an odd thing to do. Most RPC systems don't _queue_ messages, so the more we can avoid here the better.

Listeners, however, _do_ queue and acknowledge messages, as the messages there are not transient.

Therefore, for `endpoint`s we have a single handler that returns a single piece of data or a single error. Any other listeners on `data` events are just that: listeners. Awesome.

`listen`ers are the tricky part. They must acknowledge messages, but they don't need to send back any data. So, do we keep the same pattern of supplying a single `handler` that is responsible for acknowledging the message, or do we make _everything_ fall back on `on('data', ...)` listeners?

If the latter, would it be pertinent to then wait for every single listener to "complete"?

Lordy I just don't know.

**Comment by jacktuck** [comment]
> So, do we keep the same pattern of supplying a single handler that is responsible for acknowledging the message, or do we make everything fall back on on('data', ...) listeners?

I would make it so that `.on()` is completely dumb, has no knowledge of acks or callbacks -- and the only thing that can ack is the singular handler and if you register a listener OR an endpoint without a handler IMO we should throw.

**Comment by jpwilliams** [comment]
Right. Think I agree; if you need to wait for other actions to finish before acking, make a second listener.

So if we then go ahead and register a listener or an endpoint without a `handler`, when do we throw? Currently, the endpoint/listener will start "setting up" (creating channels, consuming, etc) as soon as it's created via `remit.endpoint('foo')`. Handlers are added in a chain like so: `remit.endpoint('foo').handler(...)`.

So, we can't _immediately throw_ if there's no handler present. Does this mean we'd need a `.start()` function so we have time to create handlers, map them and _then_ boot up the endpoint/listener?

Doing that does make sense to me, as it would be a nice feature to be able to `.stop()` them, halting consumption and "closing down" the endpoint/listener.

**Comment by jpwilliams** [comment]
Maybe, then, we switch it so creating an endpoint requires a handler, just like Remit v1.

``` js
const endpoint = remit.endpoint('foo', (event) => {
  return 'foobar'
})
```

**Comment by jpwilliams** [comment]
Going with this design for endpoints and listeners in the new `v2` branch.

We'll work on implementing `.stop()`, `.pause()` and `.resume()` later.
