### ISSUE TITLE
Is it worth hiding implementation details?

### ISSUE THREAD

**Issue by jacktuck** [jpwilliams/remit#47]
Is it worth using symbols or weakmaps for functions we'd rather not leak?

http://fitzgeraldnick.com/2014/01/13/hiding-implementation-details-with-e6-weakmaps.html

**Comment by jpwilliams** [comment]
That would be super cool! Big fan of that idea.

**Comment by jpwilliams** [comment]
Weakmaps could work, but hiding internal _functions_ becomes a grim game of duplicating/binding functions, giving the app a potentially-massive memory footprint.

**Comment by jacktuck** [comment]
Don't think this holds much merit.
